name: tascli
description: TasCli is an open-source task-manager like monday.com, but for command line lovers.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^1.6.0
  prompts: ^1.3.1
  colorize: any
